apiVersion: v1
kind: Service
metadata:
  name: app-service2
spec:
  selector:
    app: auth-login
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: LoadBalancer

