# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appEnvironment: __ENVIRONMENT__ ## dp
appName: process-loan
sourceCode: golang ### dp
gitlabProject: "__GITLAB_PROJECT__"
gcpProject: 
  nonprd: credit-core-backend-nonprd
  prd: credit-core-backend-prd
contextPath: /process-loan #dp

image:
  url: 
    nonprd: us-east1-docker.pkg.dev/credit-core-backend-nonprd/camunda-nonprd/process-loan
    prd: us-east1-docker.pkg.dev/credit-core-backend-prd/camunda-prd/process-loan ### dp
  pullPolicy: Always ### dp

nameOverride: ""
#fullnameOverride: __RELEASE_NAME__

hpa:
  replicaCount: 2 ### hpa, dp
  maxReplicaCount: 10 ### hpa,
  memoryAverageUtilization: 80
  cpuAverageUtilization: 80
pdb: 
  minAvailable: 1
service:
  type: ClusterIP ### svc
  port: 8080 ### svc
  targetPort: 8080 ### dp, svc
  grpcPort: 50051
  grpcTargetPort: 50051

serviceAccount:
  name: process-loan


gsm:
  enabled: true
  secretStore: process-loan-gsm-ss ### vars
  externalSecret:
    - name: es-process-loan-camunda
      k8sTarget: secret-process-loan-camunda
      secretKey: camunda-__ENVIRONMENT__
      refreshInterval: "1m"
    #- name: es-process-loan-apigee
    #  k8sTarget: secret-process-loan-apigee
    #  secretKey: apigee-cred-__ENVIRONMENT__
    #  refreshInterval: "1m"

gitlab:
  enabled: true
  secretStore: process-loan-gl-ss ### vars
  externalSecret:
    - name: process-loan-gl-token-vars
      k8sTarget: process-loan-gl-token-vars
      secretKey: ENV_VARS___ENV__
      refreshInterval: "1m"

variables:
  enabled: true
  values:
    - name: ENABLE_PAYLOAD_LOGGING
      value: "true"
    - name: LEVEL_LOGGING
      value: "INFO"
    - name: CONTEXT_PATH
      value: "/process-loan"
    - name: HTTP_SERVER_PORT
      value: "8080"
    - name: GRPC_SERVER_PORT
      value: "50051"


resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

livenessProbe:
  path: /healthCheck ### dp 
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthCheck ### dp
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3


otelCollector: "http://otel-collector.monitoring:4317" ### dp

# Valores para la configuracion del istio

istio:
  enabled: true
  workloadIdentityExclude: 169.254.169.254/32 ### dp 
  uriRules:
    - Rule:
        prefix: '/process-loan-__ENVIRONMENT__/'
        rewrite: '/process-loan/'
  annotations: {}
  path: /
  hosts:
    nonprd:
      - "credit-nonprd.endpoints.credit-core-backend-nonprd.cloud.goog"
    uat:
      - "credit-uat.endpoints.credit-core-backend-nonprd.cloud.goog"
    prd:
      - "credit-prd.endpoints.credit-core-backend-prd.cloud.goog"
  gateways:
    - "asm-ingress/asm-ingressgateway"

hostAliases : {}
nodeSelector: {}
tolerations: []
affinity: {}
