apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ .Values.appName}}
  name: {{ .Values.appName}}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.appName}}
