{{- if .Values.gsm.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.gsm.secretStore }}
spec:
  provider:
    gcpsm:
      projectID: "{{- if eq .Values.appEnvironment "prd" -}}{{ .Values.gcpProject.prd }}{{- else -}}{{ .Values.gcpProject.nonprd }}{{- end }}"
{{- end }}
---
{{- if .Values.gsm.enabled }}
{{- range .Values.gsm.externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.gsm.secretStore }}
  target:
    name: {{ .k8sTarget }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .secretKey }}
---
{{- end }}
{{- end }}