---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    iam.gke.io/gcp-service-account: "{{- if eq .Values.appEnvironment "prd" -}}{{ .Values.serviceAccount.name }}@{{ .Values.gcpProject.prd }}.iam.gserviceaccount.com{{- else -}}{{ .Values.serviceAccount.name }}@{{ .Values.gcpProject.nonprd }}.iam.gserviceaccount.com{{- end }}"
  name: {{ .Values.serviceAccount.name }}

