apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName}}
    version: "v{{ .Chart.AppVersion }}"
    app.kubernetes.io/name: {{ .Values.appName}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.port }}
    - name: grpc
      targetPort: {{ .Values.service.grpcTargetPort }}
      port: {{ .Values.service.grpcPort }}
  selector:
    app: {{ .Values.appName}}
    app.kubernetes.io/name: {{ .Values.appName}}
    app.kubernetes.io/instance: {{ .Release.Name }}
