{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: "v{{ .Chart.AppVersion }}"
    chart: {{ .Chart.Name }}
    release: {{ .Values.appName}}
spec:
  hosts:
  {{- if eq .Values.appEnvironment "prd" -}}
    {{- toYaml .Values.istio.hosts.prd | nindent 2 }}
  {{- else if eq .Values.appEnvironment "uat" -}}
    {{- toYaml .Values.istio.hosts.uat | nindent 2 }}
  {{- else -}}
    {{- toYaml .Values.istio.hosts.nonprd | nindent 2 }}
  {{- end }}
  gateways:
  {{- toYaml .Values.istio.gateways | nindent 4 }}
  http:
  {{- range $_, $rules := .Values.istio.uriRules }}
    - match:
        - uri:
            prefix: {{ $rules.Rule.prefix }}
      rewrite:
        uri: {{ $rules.Rule.rewrite }}
      route:
        - destination:
            port:
              number: {{ $.Values.service.port }}
            host: "{{ $.Values.appName}}.{{ $.Release.Namespace }}.svc.cluster.local"
  {{- end }}
{{- end }}

