apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName}}-grpc
  labels:
    app: {{ .Values.appName}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: "v{{ .Chart.AppVersion }}"
    chart: {{ .Chart.Name }}
    release: {{ .Values.appName}}
spec:
  hosts:
  -  "{{ .Values.appName}}.{{ $.Release.Namespace }}.svc.cluster.local"
  gateways:
  {{- toYaml .Values.istio.gateways | nindent 4 }}
  tcp:
    - match:
      - port: {{ $.Values.service.grpcPort }}
      route:
      - destination:
          port:
            number: {{ $.Values.service.grpcPort }}
          host: "{{ .Values.appName}}.{{ $.Release.Namespace }}.svc.cluster.local"